pipeline {
    agent any
    environment {
        NEW_VERSION = '1.3.0'
    }
    stages {
        stage("build"){
            
            steps {
                echo 'building the application'
            }
        }

        stage("test"){
            steps {
                echo 'Testing the application'
                echo "testing version ${NEW_VERSION}"
            }
        }

        stage("deploy"){

            steps {
                echo 'Deploying the application'
            }
        }
    }
}